### PR TITLE
fix: add NetBSD support

### PR DESCRIPTION
**Pull request by 0323pin**
Hi,

I've packaged `matugen` for NetBSD and will merge the package tomorrow morning, it's getting late here :)

Here it is running on my system,
2023-08-05-224827_1366x768_scrot

Please consider the patches provided allowing the build on NetBSD.

Some build warnings issued with Rust-1.71.1 you might already be aware of but, leaving them here anyway

```
   Compiling ini-material-color-utilities-rs v0.3.0 (/usr/pkgsrc/wip/matugen/work/Matugen-matugen-v0.8.3/material-color-utilities-rs)
warning: unused import: `linearized`
 --> material-color-utilities-rs/src/htc/cam16.rs:4:41
  |
4 | use crate::util::color::{argb_from_xyz, linearized, xyz_from_argb};
  |                                         ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: associated function `new` is never used
   --> material-color-utilities-rs/src/htc/cam16.rs:119:8
    |
34  | impl Cam16 {
    | ---------- associated function in this implementation
...
119 |     fn new(
    |        ^^^
    |
    = note: `#[warn(dead_code)]` on by default

   Compiling paris-log v1.0.2
   Compiling resolve-path v0.1.0
   Compiling directories v5.0.1
   Compiling toml v0.7.3
warning: `ini-material-color-utilities-rs` (lib) generated 2 warnings (run `cargo fix --lib -p ini-material-color-utilities-rs` to apply 1 suggestion)
   Compiling pretty_env_logger v0.4.0
   Compiling colorsys v0.6.7
   Compiling matugen v0.8.3 (/usr/pkgsrc/wip/matugen/work/Matugen-matugen-v0.8.3)
warning: unused import: `ValueEnum`
 --> src/util/arguments.rs:1:48
  |
1 | use clap::{arg, ArgAction, Parser, Subcommand, ValueEnum};
  |                                                ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `util::color::format_argb_as_rgb`
 --> src/util/color.rs:1:51
  |
1 | use material_color_utilities_rs::{scheme::Scheme, util::color::format_argb_as_rgb};
  |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `Color`
 --> src/main.rs:8:25
  |
8 |     color::{show_color, Color},
  |                         ^^^^^

warning: unused imports: `ColorTransform`, `SaturationInSpace`
  --> src/main.rs:24:28
   |
24 | use colorsys::{ColorAlpha, ColorTransform, Hsl, Rgb, SaturationInSpace};
   |                            ^^^^^^^^^^^^^^            ^^^^^^^^^^^^^^^^^

warning: unused import: `color`
  --> src/main.rs:27:12
   |
27 | use util::{color, reload::reload_apps_linux, wallpaper::set_wallaper};
   |            ^^^^^

warning: `matugen` (bin "matugen") generated 5 warnings (run `cargo fix --bin "matugen"` to apply 5 suggestions)
    Finished release [optimized] target(s) in 4m 06s
```

### CODE REVIEW

**Comment by 0323pin** [comment]
oh, sorry. Should add that only `feh` is supported on NetBSD. Even though, I've added all the other options to allow the build.

**Comment by InioX** [comment]
Hi,

I really appreciate the pull request! There's just one thing I would like to change. 

I know it might seem annoying, but it would be nice if the https://github.com/InioX/Matugen/pull/9/commits/5fcfa82cad5c1d251e0f4733e87947051604ca14 commit message used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) format instead.

Also, thanks for the heads-up on warnings.

**Comment by 0323pin** [comment]
That's fine, do you see it as `fix:` or, `build:`?
Obviously, once I merge the package, it will become available for users to install.

Would you like to have that in the README.MD also?

**Comment by 0323pin** [comment]
For your reference, here is the package merge log, http://mail-index.netbsd.org/pkgsrc-changes/2023/08/06/msg280244.html

**Comment by InioX** [comment]
I see it more of a `fix:` since i forgot about adding it when i wrote the code originally.

The new release was just a small patch to fix some lock file stuff.

About the commit name, have you tried following [this](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#amending-older-or-multiple-commit-messages)? If it's actually impossible to change it, you should open a new PR. I think it should be done as a last resort, though.

Again, I'm really sorry if it's annoying and i understand that. But it's mainly for `release-plz`.

**Pull request closed without merging**
