### PR TITLE
Feat: Remove `reload_apps`-related functionality and add a `config.wallpaper` section

### PR DESCRIPTION
**Pull request by ys5g**
Makes way for #68 and makes #94 obsolete
Basically, it adds a `config.wallpaper` section and removes the `config.reload_apps` option and the entire `config.reload_apps_list` section.
The path to the image doesn't need to be specified in `config.wallpaper.arguments`. It'll be the last argument provided to the command automatically 
Example configuration:
```toml
[config.wallpaper]
arguments = ["img", "--transition-type", "center"]
command = "swww"
set = true

[templates.gtk3]
input_path = "./templates/gtk.css"
output_path = "$HOME/.config/gtk-3.0/gtk.css"
[templates.gtk4]
input_path = "./templates/gtk.css"
output_path = "$HOME/.config/gtk-4.0/gtk.css"
```
<details>
  <summary>Nix configuration(at least with #68)</summary>

```nix
programs.matugen.settings.config.wallpaper = {
  set = true;
  command = "${lib.getExe pkgs.swww}";
  arguments = [
    "img"
    "--transition-type"
    "center"
  ];
};
```
</details>

### CODE REVIEW

**Comment by DaniD3v** [comment]
How could I add a reload_app hook here?
I can't execute 2 commands with this, right?

I know it's a bit late for discussion now but I would've preferred using the templating engine on commands as well rather than just having an args array and adding the image path at the end. Take a look at this use case for example:

```
PRIMARY_COLOR=$(${pkgs.matugen}/bin/matugen image ''${wallpaper} --json strip | ${pkgs.jq}/bin/jq -r ".colors.light.primary")
asusctl led-mode static -c "$PRIMARY_COLOR" # asusctl is installed system-wide so I can't use an absolute path.
```

This would be 30 times easier with a hook that can be templated.

**Comment by ys5g** [comment]
`reload_apps` wasn't customizable for the end-user anyway, and everything is being reimplemented at the matugen-themes repo. 
Also, why would you execute 2 commands to set a wallpaper? I only included `config.wallpaper.pre_hook`, which supports running multiple commands and templating, so you can `pkill` your wallpaper daemon.
Unless I'm missing something, that code block doesn't have anything to do with settings a wallpaper or `reload_apps` so IDT this PR affected your ability to run that.

**Comment by DaniD3v** [comment]
Isn't the thingy that sets a wallpaper basically just a pre_hook? Why not just add templating there and remove this entirely?

**Comment by ys5g** [comment]
If you mean using `templates`, you _need_ `input_path` and `output_path`, which doesn't make sense with wallpapers. If you mean adding a `config.run_after` option that accepts templating and multiple commands, it looks like that was considered but then removed([wiki link](https://github.com/InioX/matugen/wiki/Configuration#configuration-items)).
At the end of the day, it seems like multiple ways of doing the same thing so idk

**Pull request merged**
